# Each sevice listed will be deployed in its own container as part of your
#    Platform.sh project.

db:
    type: "postgresql:15"
    disk: 512
    endpoints:
        database:
            public: false